### ISSUE TITLE
Tests?

### ISSUE THREAD

**Issue by niemeyer** [milochristiansen/lua#1]
Really happy to see a Lua 5.3 interpreter in Go with focus in isolation, thanks for publishing it!

One thing that worries me over a quick inspection is the complete lack of tests. I realize you have external code that exercises it, but having a language implementation that is completely untested means passers by cannot hack opportunistically without being entirely unaware of whether something broke or not.

What are your plans in those terms?  Do you intent to add a test suite?  Are there any upstream tests that we might leverage?

Thanks again.

**Comment by milochristiansen** [comment]
My current test code is all written to exercise another DSL, which also exercises the Lua VM purely as a side effect. This is obviously suboptimal.

Any tests would need to be written from scratch, and I don't really have time to do that right now. I would like to add proper tests at some point, but I just don't see it happening for a few months at least.

Obviously now that I have released the code into the wild tests have a far higher priority than they did when the code was in use by just me :) Needless to say contributions are welcome, but I won't be counting on them...

**Comment by niemeyer** [comment]
Have you see these: https://www.lua.org/tests/#complete

I'm sure some stuff would have to be ported to not assume undefined behavior, but this looks like a good way to bootstrap without too much work, and perhaps even catch discrepancies worth knowing about.

**Comment by niemeyer** [comment]
This is probably worth looking into as well: https://github.com/LuaJIT/LuaJIT-test-cleanup

**Comment by milochristiansen** [comment]
Currently I am working on some basic tests to check the native VM API, but I do plan to use script tests based on the official Lua tests to cover everything else.

Thanks for the link, that will save me from having to look it up myself :)

**Comment by milochristiansen** [comment]
I'll go ahead and close this now. The latest version adds some tests, and (many) more are on the way.
