### ISSUE TITLE
Major internal error, this indicates an internal VM bug! Attempt to get out of range upvalue!

### ISSUE THREAD

**Issue by jeff-emanuel** [milochristiansen/lua#11]
First, thanks for making this implementation available.  I've run into a problem.

The attached code causes the following panic:

panic: Major internal error, this indicates an internal VM bug! Attempt to get out of range upvalue!

goroutine 1 [running]:
github.com/milochristiansen/lua/luautil.Raise(0x5254b1, 0x24, 0x1)
        c:/dev/go/src/github.com/milochristiansen/lua/luautil/errors.go:82 +0xa0
github.com/milochristiansen/lua.(*callFrame).getUp(0xc042011040, 0x1, 0xc042009a70, 0x510280)
        c:/dev/go/src/github.com/milochristiansen/lua/callframe.go:93 +0x58
github.com/milochristiansen/lua.init.1.func7(0xc0420340e0, 0xc000c24006, 0xc042010f00)
        c:/dev/go/src/github.com/milochristiansen/lua/vm.go:168 +0x59
github.com/milochristiansen/lua.(*State).exec(0xc0420340e0)
        c:/dev/go/src/github.com/milochristiansen/lua/vm.go:81 +0x129
github.com/milochristiansen/lua.(*State).call(0xc0420340e0, 0x0, 0x0, 0x0, 0xc042002800)
        c:/dev/go/src/github.com/milochristiansen/lua/vm.go:66 +0x109
github.com/milochristiansen/lua.(*State).Call(0xc0420340e0, 0x0, 0x0)
        c:/dev/go/src/github.com/milochristiansen/lua/api.go:1014 +0x5c

Reducing the number of elements in the forward array results in this panic:

panic: Value is not a function and has no __call meta method.

goroutine 1 [running]:
github.com/milochristiansen/lua/luautil.Raise(0x52711d, 0x36, 0x4)
        c:/dev/go/src/github.com/milochristiansen/lua/luautil/errors.go:82 +0xa0
github.com/milochristiansen/lua.(*State).call(0xc04206c070, 0x0, 0x1, 0x3, 0x0)
        c:/dev/go/src/github.com/milochristiansen/lua/vm.go:57 +0x2c2
github.com/milochristiansen/lua.init.1.func22(0xc04206c070, 0xc001010024, 0xc04206ae00)
        c:/dev/go/src/github.com/milochristiansen/lua/vm.go:400 +0x7a
github.com/milochristiansen/lua.(*State).exec(0xc04206c070)
        c:/dev/go/src/github.com/milochristiansen/lua/vm.go:81 +0x129
github.com/milochristiansen/lua.(*State).call(0xc04206c070, 0x0, 0x0, 0x0, 0xc042054400)
        c:/dev/go/src/github.com/milochristiansen/lua/vm.go:66 +0x109
github.com/milochristiansen/lua.(*State).Call(0xc04206c070, 0x0, 0x0)
        c:/dev/go/src/github.com/milochristiansen/lua/api.go:1014 +0x5c

Using a very small array works correctly.

I'm running go version go1.8.1 windows/amd64 and revision 912ce85dfa7a1713c434108bab1af2963938bfb8 (v 1.1.5) from this repository.

[reverseluaarray.zip](https://github.com/milochristiansen/lua/files/1945187/reverseluaarray.zip)

**Comment by milochristiansen** [comment]
Thank you for the report (it look nice and detailed too, so extra thanks for that). I'll take a look at it and hopefully have a fix up by this time tomorrow or before (and if not I'll at least have some info to post here).

**Comment by milochristiansen** [comment]
The error turns out to be an issue with the compiler, your code runs fine if an external compiler is used (for example, via `LoadTextExternal`). I have not identified why these specific instructions are generating incorrectly yet, but it *should* be a straightforward fix once I identify where exactly it is going wrong.

**Comment by jeff-emanuel** [comment]
Thanks for the rapid feedback

**Comment by milochristiansen** [comment]
In the light of morning the probable cause of the problems is pretty obvious, it seems there are so many constants that it is overflowing the RK value in the `C` field of the `GETTABUP` instruction. For some reason I never checked for constant overflow and emitted the proper instructions to load the constant properly.

There is actually a TODO at the top of the file to remind me that this isn't implemented :/ The good news is that it *will* be working by tonight.

**Comment by jeff-emanuel** [comment]
In that case, this might not be the same as my original problem.  The large number of constants came about in creating a concise demonstration.  I'll see if I can factor my original use case differently.

**Comment by milochristiansen** [comment]
Either way, this particular issue will be fixed shortly. As soon as it is gone there is a good chance your original issue will spring up. I did notice the second stack trace you posted seems unrelated to constant overflow (although I could be wrong).

**Comment by milochristiansen** [comment]
If that does not solve your problem, please open a new issue.
