### ISSUE TITLE
Failure chaining function call and table accesses

### ISSUE THREAD

**Issue by jeff-emanuel** [milochristiansen/lua#13]
This code works in Lua 5.3.4:

Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio
> function A() return {"a",{X="x"}} end
> print(A()[2].X)
x

Here the X access yields nil, but it works when using an intermediate variable such as:

> function A() return {"a",{X="x"}} end
> u=A()[2]
> print(u.X)
x

See attached code.
[luatablefunction.zip](https://github.com/milochristiansen/lua/files/1973093/luatablefunction.zip)

**Comment by milochristiansen** [comment]
Sounds like yet another compiler bug. I'll check it out tonight.

**Comment by jeff-emanuel** [comment]
Thanks

**Comment by milochristiansen** [comment]
OK, I confirmed it to be a compiler error, the generated code is inexplicably missing the instruction to do the first index operation (the `[2]` part), although it generates everything else correctly. I as of yet do not know why it is missing this bit, but it shouldn't be too hard to track it down.

I'll have a fix up soon, AKA within a few hours of me waking up tomorrow (I'm a bit tired right now).

Honestly, I was *sure* I had all the stupid little edge case bugs squashed long ago, but it seems the compiler is the gift that keeps on giving :P In any case, I am grateful for every bug that is reported, each one found and fixed makes the package just a little bit better.

**Comment by milochristiansen** [comment]
OK, so this is proving harder than expected. Normally *finding* the issue is pretty easy, and *fixing* it is the "hard" part. This time I'm having trouble identifying what is causing the issue. I'll get it sooner or later, but not as soon as I expected. Sorry.

**Comment by milochristiansen** [comment]
Tests pass, and the example provided works. The bug would probably also effect expressions in parenthesis followed by table accessors, not just function calls followed by accessors, but both should work now.

Once I figured out where the problem was fixing it was pretty trivial, just as expected.

**Comment by jeff-emanuel** [comment]
It works great.  Thanks so much!
