### ISSUE TITLE
Vendored sliceutil breaks with go modules

### ISSUE THREAD

**Issue by mgilbir** [milochristiansen/lua#18]
When go getting the package in a project using go modules in go1.11, I get:

```
$ go get "github.com/milochristiansen/lua"
go: finding github.com/milochristiansen/lua v1.1.6
go: downloading github.com/milochristiansen/lua v1.1.6
go build sliceutil: no Go files in
```

When building, the error is `cannot find module for path sliceutil`

Possible solutions would be, bringing the `sliceutil` package into the project (out of the vendor directory), or if `sliceutil` is meant to be an external dependency it could be made available in another repo.

**Comment by milochristiansen** [comment]
Yeah, that package is a lazy hack I pulled in from some of my private code. I should either integrate it properly or just redo the places that use it to be less hacky.

One way or another it will be gone either today or tomorrow.

**Comment by mgilbir** [comment]
Wow. Thanks for the quick fix! 🙇
