### ISSUE TITLE
Raise error when compare integer with float.

### ISSUE THREAD

**Issue by erdian718** [milochristiansen/lua#22]
In State.compare:
fa, oka := a.(float64)
fb, okb := b.(float64)
should be:
fa, oka := tryFloat(a)
fb, okb := tryFloat(b)

**Comment by milochristiansen** [comment]
Do you have some script code that actually triggers an error there? To hit one of those lines the Lua type of `a` and `b` must both be `number`, meaning that they are either `int64` or `float64` underlying types.

The reference Lua VM tries to compare as ints or floats if both values are the same underlying number type, and falls back to integer comparison if the types do not match, exactly like this code does. Unless it is crashing, I'm pretty sure this is operating to spec.

**Comment by erdian718** [comment]
https://github.com/ofunc/lua/blob/master/test/math.lua

test.random:
assert(0 <= r and r < 1)

**Comment by milochristiansen** [comment]
Cool. (Well, not cool, but you know what I mean)

I'll have that fixed up sometime tonight yet.

**Comment by milochristiansen** [comment]
This no longer crashes, but it isn't 100% correct. `5.1 > 5` will probably be false. I need to investigate exactly how the reference code works again.
