### ISSUE TITLE
A syntax error

### ISSUE THREAD

**Issue by erdian718** [milochristiansen/lua#23]
Run code `({}).test = 123`, got an error: Invalid token: Found: . Expected: {, <string>, or ( On Line: 2

**Comment by milochristiansen** [comment]
Ok, that error message can only come from one spot, so that helps a lot. For some reason the parser thinks it is a function call, which is nonsensical of course. I'll trace it back and see where it goes wrong, should be a simple fix (I hope).

**Comment by milochristiansen** [comment]
There was a bit of code that looked for a parenthesized expression and assumed it was the "name" part of a function call. I have no idea why it was there, since the correct code for handling that kind of thing was in the very next check.

Needless to say, I removed it.
