### ISSUE TITLE
Examples To Write Code

### ISSUE THREAD

**Issue by n-is** [milochristiansen/lua#30]
I am trying to write a go code, that can run lua script in a file and extract the value of certain variable. Is there any way I can use this repo for this? Are there any examples that I can refer to? Thanks.

**Comment by jeff-emanuel** [comment]
https://github.com/milochristiansen/lua/blob/master/fib_test.go  runs Lua
code from a file.  To retrieve Lua variables, you'll need something like

l.Push("varname")
l.GetTable(lua.GlobalsIndex)
value := l.GetRaw(-1)

See also https://www.lua.org/pil/24.2.html

**Comment by milochristiansen** [comment]
(now that I'm home from work) There is not really a good self-contained example in the repo right now, but I can provide a simple one here:
```
err := l.LoadText(bytes.NewBuffer(`
test = "Stored in global variable"
return "Hello World!"
`), name, 0)
if err != nil {
	panic("Handle your errors!")
}

// Call code, and expect 1 return value.
err := l.PCall(0, 1)
if err != nil {
	panic("Handle your errors!")
}

// Print the returned value as a string.
fmt.Println(l.ToString(-1))
l.Pop(1)

// Now fetch the variable value and print it (once again, as a string).
l.Push("test")
l.GetTable(lua.GlobalsIndex)
fmt.Println(l.ToString(-1))
l.Pop(1)
```

**Comment by n-is** [comment]
Thanks. Is there some way that would let me pass a go map to lua script and get back a go map. Any example would be fine. Again, thanks for the help.

**Comment by milochristiansen** [comment]
You can find a bunch of code using this VM in the [Rubble repository](https://github.com/milochristiansen/rubble8/tree/master/scripting/dctech_lua), including a whole bunch of lua metatable implementations.

Down near the bottom of `metatables.go` there are implementations of metatables for `map[string]string` and `[]string`.

If you want something simpler, more generic, but more fragile, the `supermeta` package in this very repo should get you started.

**Comment by n-is** [comment]
Thanks a lot :)

**Comment by n-is** [comment]
I am getting the following error when passing a `map[string]interface{}` to the lua script using `supermeta` package in this repo.
```
panic: Unspecified error: reflect: call of reflect.Value.IsNil on zero Value
```
The trace shows the error is from `fromPtr` function in `supermeta package -> supermeta.go`. How can I pass the `map[string]interface{}` to the lua script? Thanks.

**Comment by milochristiansen** [comment]
That looks to be a simple oversight in the code. A nil interface will make `IsNil` panic, so I need to add an extra check for that. I'm snowed out of work today, so I'll have it fixed shortly.

**Comment by milochristiansen** [comment]
Ok, the crash was an oversight. `map[string]interface{}` not working was not.

It has been a long time since I worked with `supermeta`, and I had forgotten it does not support interfaces very well. In this specific case you should be able to read existing keys in the map, but writing to them won't work (you will get a "conversion not implemented" error).

`supermeta` is designed to work with concrete types with a token effort in the direction of interfaces. If you really must use a map of `interface{}` you will need to implement your own metatable.
