### ISSUE TITLE
runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by mgilbir** [milochristiansen/lua#35]
Hi,

I've found a pesky issue related to the stack growth that would trigger `runtime error: slice bounds out of range` when the requested index was just on the boundary of the slice backing the stack data.

I'll submit a test reproducing the issue and a fix.

**Comment by milochristiansen** [comment]
Me do math good. Considering this never triggered before for any of my projects, it must have needed the stars to align just *wrong* for you to have discovered this. My condolences.

Thank you very much for finding (and fixing!) this error.
