### ISSUE TITLE
Could you tag for releases?

### ISSUE THREAD

**Issue by hnakamur** [milochristiansen/lua#4]
First of all, thanks for creating and sharing a nice software!

Could you tag for releases like 1.0.1, 1.0.2 or v1.0.1, v1.0.2?

For example if tag `1.0.2` exist, you can download the tarball with the following URL.
https://github.com/milochristiansen/lua/archive/1.0.2.tar.gz

This is more convenient than
https://github.com/milochristiansen/lua/archive/{{ commit_hash }}.tar.gz
for downloading the specific version.

Thanks!

**Comment by milochristiansen** [comment]
Sure, no problem.
