### ISSUE TITLE
Licensing confirmation

### ISSUE THREAD

**Issue by TC01** [milochristiansen/lua#5]
Hi,

Would it be possible for you to stick a LICENSE file or some other indication of this project's license in this repository? The license file for Rubble states that both this and axis2 are under the same license as rubble (zlib), but there's no statement of that anywhere in *this* repository. :)

The axis2 repository, likewise, also seems to be missing a statement of what license the project is under.

Thanks in advance!

**Comment by milochristiansen** [comment]
Every single file has a license header. Every single one. That said a LICENSE file couldn't hurt anything...

I'll add one next time I upload a new version (coming soon! I just finished adding a reflection based metatable package :) Now I just need to write tests for it...)

I'll close this once I upload.

**Comment by milochristiansen** [comment]
New version (with LICENSE file) is up!
